services:
  mysql:
    image: mysql:8
    container_name: mysql-8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: redway
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    container_name: api
    build: ./backend
    restart: always
    ports:
      - 4000:4000
    depends_on: 
      - mysql
  redapp:
    container_name: redapp
    build: ./redApp
    volumes: 
      - redapp:/var/www/html
    depends_on:
      - mysql
      - api
  nginx:
    container_name: nginx
    build: ./.nginx
    ports:
      - 80:80
    volumes: 
      - redapp:/var/www/html
    depends_on:
      - mysql
      - api
      - redapp
volumes:
  redapp:
  mysql:
